name: CICD-Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Dockerhub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:$IMAGE_TAG ./app
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${IMAGE_TAG}
      
    - name: Update Kubernetes manifests with new image tag
      run: |
        sed -i "s#image: .*#image: ${{ secrets.DOCKER_USERNAME }}/flask-app:${IMAGE_TAG}#g" k8s/deployment.yml

    - name: Commit updated manifest
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.email "shobhitnagar71@gmail.com"
        git config user.name "Shobhit0398"
        git add k8s/deployment.yml
        git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes"
        git push https://$GH_PAT@github.com/Shobhit0398/docker-multistage-demo.git HEAD:master